# BIOMAG introduction material 2. - Pytorch basics - Tensors

A tensor is a basic datatype in pytorch (and all other deep learning frameworks as well). They are basically n-dimensional matrices which can be really beneficial when using them on the GPU.

In [19]:
import torch
import numpy as np

First, let us see ho we can convert between the most well known array-like structures:

In [20]:
data = [[1,2],[3,4]]
print(type(data))

<class 'list'>


In [21]:
torch_data = torch.tensor(data)
print(torch_data)
print(type(torch_data))

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [22]:
np_data = np.array(data)
print(np_data)
print(type(np_data))
torch_data = torch.from_numpy(np_data)
print(torch_data)
print(type(torch_data))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


By default, all of the tensor data operations are carried out on the CPU:

In [23]:
torch_data.device

device(type='cpu')

Now let us see some basic tensor operations:

In [25]:
tensor_1 = torch.tensor([[1,2,1],
                        [0,1,1],
                        [0,4,1]])
tensor_2 = torch.tensor([[1,0,1],
                        [0,1,1],
                        [0,0,1]])

In [27]:
print(tensor_1 + tensor_2)
print(tensor_1 - tensor_2) 
print(tensor_1 * tensor_2)
print(tensor_1 @ tensor_2) # what's the difference compared to the previous one?
print(tensor_1.sum())

tensor([[2, 2, 2],
        [0, 2, 2],
        [0, 4, 2]])
tensor([[0, 2, 0],
        [0, 0, 0],
        [0, 4, 0]])
tensor([[1, 0, 1],
        [0, 1, 1],
        [0, 0, 1]])
tensor([[1, 2, 4],
        [0, 1, 2],
        [0, 4, 5]])
tensor(11)


But when are tensors useful the most? Why do we need them instead of using numpy arrays?

In [29]:
import time

In [30]:
tensor_1 = torch.rand((3,2048,2048,4))

In [31]:
tensor_2 = torch.rand((4,64))

In [32]:
t = time.time()
tensor_1@tensor_2
elapsed = time.time() - t
print(elapsed)

0.583681583404541


In [34]:
tensor_1 = tensor_1.to('cuda')
tensor_2 = tensor_2.to('cuda')
print(tensor_1.device)


cuda:0


In [35]:
t = time.time()
tensor_1@tensor_2
elapsed = time.time() - t
print(elapsed)

0.010904788970947266


### Homework

1. Try to visualize the difference between using a GPU or a CPU for tensor operations using matplotlib, with ever incresing tensor sizes.
2. Write a function that takes a 2D vector as input and performs a 2D transformation (a combination of rotation, translation, scaling) on the vector using only matrix multiplication, using only pytorch datatypes and pytorch math operations. (Look for homogeneous coordinates)